runtime: php55
api_version: 1

includes:
- client_secrets.yaml

handlers:
- url: /
  script: index.php

- url: /index.php
  script: index.php

- url: /process_steam_data
  script: steam_data_processor.php
  login: admin

- url: /ajax_handler.php
  script: ajax_handler.php

- url: /stylesheets
  static_dir: stylesheets

- url: /javascript
  static_dir: javascript

- url: /.*
  script: not_found.php